---
version: 0.2

phases:
  install:
    commands:
      - |
        if [ "${SPEL_CI}" = "true" ]
        then
          SPEL_VERSION=$(date +%Y.%m.dev%s)
          export SPEL_VERSION
        fi
  build:
    commands:
      - make
  post_build:
    commands:
      - make post_build
      - find . -type f \( -name '*.box' -o -name '*.ova' \) -print0 | xargs -0 rm -f

artifacts:
  files:
    - '**/*'
  base-directory: '.spel'
